#!/usr/bin/env python3
"""
scripts/generate_python_docs.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Auto-generate Markdown API reference docs for every Python CLI entry-point
defined in pyproject.toml [project.scripts].

Strategy
────────
For each console_scripts entry the script:
  1. Imports the module (no execution — argparse is only invoked on --help).
  2. Locates the `main()` function callable.
  3. Captures both:
        • the module / function docstring (rendered as Description prose)
        • the `--help` output rendered by argparse (rendered as a fenced code block)
  4. Extracts structured argument metadata (name, type, metavar, choices, help)
     directly from the argparse formatter rather than parsing plain text.
  5. Writes four-section Markdown file matching the PowerShell generator format:
        docs/python/generated/<console_script_name>.md
  6. Builds / refreshes docs/python/generated/INDEX.md.

Output format (mirrors Generate-PSDocs.ps1 structure):
  ---
  source:      automation.cli.foo::main()
  console_script: <name>
  generated:   <timestamp>
  auto_generated_by: scripts/generate_python_docs.py
  ---
  # `<name>`
  ## Description          ← module docstring, if present
  ## Parameters           ← argparse-derived name / type / description table
  ## Examples             ← usage-prose extracted from argparse help
  ## Help                 ← raw argparse --help output in fenced shell block
  ---
  *This file is auto-generated by `scripts/generate_python_docs.py`. Do not edit directly — update code or docstrings and re-run.*
  ---
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Usage
─────
  uv run python scripts/generate_python_docs.py
  uv run python scripts/generate_python_docs.py --force      # overwrite existing .md files
  uv run python scripts/generate_python_docs.py --output docs/custom

Prerequisites
─────────────
  pip install -e .   (project must be on sys.path with its dependencies)

Jenkins
───────
  sh '''
    python3 scripts/generate_python_docs.py --force
  '''
  archiveArtifacts artifacts: 'docs/python/generated/**'
"""

from __future__ import annotations

import argparse
import importlib
import io
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ── Config ─────────────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = PROJECT_ROOT / "src"
DOCS_OUTPUT_DIR = PROJECT_ROOT / "docs" / "python" / "generated"
DOCS_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Mirror [project.scripts] from pyproject.toml — single source of truth.
CONSOLE_SCRIPTS: dict[str, str] = {
    "build-iso": "automation.cli.build_iso:main",
    "update-firmware": "automation.cli.update_firmware_drivers:main",
    "patch-windows": "automation.cli.patch_windows_security:main",
    "deploy-server": "automation.cli.deploy_to_server:main",
    "monitor-install": "automation.cli.monitor_install:main",
    "opsramp": "automation.cli.opsramp_integration:main",
    "maintenance-mode": "automation.cli.maintenance_mode:main",
    "generate-uuid": "automation.cli.generate_uuid:main",
}


# ── Data model ────────────────────────────────────────────────────────────────
@dataclass
class CmdDoc:
    """Structured doc for one console-script command."""

    script_name: str
    module_path: str
    function_name: str
    docstring: str | None
    help_text: str
    arg_table: list[dict[str, Any]] = field(default_factory=list)  # structured arg metadata
    raw_help: str = ""


# ── Helpers ───────────────────────────────────────────────────────────────────
def load_callable(dotted: str) -> tuple[Any, str]:
    """Import a module and return (callable, module_path)."""
    module_path, _, func_name = dotted.partition(":")
    mod = importlib.import_module(module_path)
    fn = getattr(mod, func_name)
    return fn, module_path


def _is_true_bool_action(action: argparse.Action) -> bool:
    """Return True if this is a store_true / store_false boolean flag (no metavar)."""
    return isinstance(action, (argparse._StoreTrueAction, argparse._StoreFalseAction,
                               argparse._StoreConstAction, argparse._AppendConstAction,
                               argparse._CountAction))


def _action_name(action: argparse.Action) -> str:
    """Return the canonical flag name without '-' prefix.

    Prefers the longest option string so that ``'-c', '--cluster-id'`` yields
    ``'cluster-id'`` rather than ``'c'``.  For positional args returns
    ``action.dest``.
    """
    strings = action.option_strings
    if strings:
        return max(strings, key=len).lstrip("-")
    return action.dest


def _action_has_short(action: argparse.Action) -> bool:
    """Return True if there is a short single-char alias."""
    return any(len(s) == 2 and s[0] == "-" for s in action.option_strings)


def _action_choices(action: argparse.Action) -> list[str] | None:
    """Return string choices list if action has one, else None."""
    ch = action.choices
    if ch is None:
        return None
    if isinstance(ch, (list, tuple)):
        return [str(x) for x in ch]
    if isinstance(ch, dict):
        return [str(k) for k in ch]
    return [str(ch)]


def _action_default_str(action: argparse.Action) -> str | None:
    """Return a readable default value, or None if action has no default."""
    # Boolean flags (store_true/false) don't carry a useful default in help;
    # argparse shows "(default: False)" for store_true at terminal width 80 but
    # omits it at 120+. We follow Python convention and skip explicit defaults
    # for store_true / store_false.
    if _is_true_bool_action(action):
        return None
    if action.default is argparse.SUPPRESS:
        return None
    if action.default is None:
        return None
    return str(action.default)


def _action_type_str(action: argparse.Action) -> str | None:
    """Return the type name for display, e.g.  'str', 'int', 'Path', 'float'."""
    if _is_true_bool_action(action):
        return None
    if action.type is None:
        return None
    if isinstance(action.type, argparse.FileType):
        return action.type._mode  # 'r' / 'w' etc.
    tname = getattr(action.type, "__name__", None) or str(action.type)
    return tname


def _action_opt_str(action: argparse.Action) -> str:
    """Build the option-type string shown in the Parameters table, e.g.
    '--iso-dir ISO_DIR, -o OUTPUT_DIR'  or  '--dry-run'  or  '--method {ilo,redfish}'."""
    # Identify the long and short options regardless of the order stored by argparse.
    # argparse uses real_longs set to collect Option objects from the option_tree,
    # then calls _build_action with that set.  What we care about is: which entry in
    # option_strings looks like '--FLAG' (length > 2 + leading '--'), and which looks
    # like '-X' (length == 2 + leading '-').
    strings = action.option_strings
    long_opts  = [s for s in strings if len(s) > 2 and s.startswith("--")]
    short_opts = [s for s in strings if len(s) == 2 and s.startswith("-")]

    # ---------- paired or standalone long option ----------
    if _is_true_bool_action(action):
        # Boolean flag: no metavar — just show the long form, or the only form.
        return (long_opts[0] if long_opts
                else short_opts[0] if short_opts
                else strings[0] if strings
                else "")

    # Determine the metavar or choices-inline for the type spec.
    # When choices are defined and no explicit metavar is given, show them as
    # '{c1, c2}' in the type table rather than the generic DEST.upper() string.
    metavar = action.metavar
    if metavar is None:
        metavar = None if action.nargs == 0 else (action.choices is not None and _action_inline_choices(action)) or action.dest.upper()

    type_parts: list[str] = []

    # Long form: always present if we found any.
    if long_opts:
        type_parts.append(f"{long_opts[0]} {metavar}" if metavar else long_opts[0])

    # Short form + metavar.
    if short_opts and metavar:
        type_parts.append(f"{short_opts[0]} {metavar}")
    elif short_opts:
        type_parts.append(short_opts[0])

    # Inline choices in the type spec (e.g. --method {ilo,redfish}).
    ch = _action_inline_choices(action)
    if ch:
        type_parts.insert(0, ch)   # choices go at the front

    return ", ".join(type_parts)


def _action_inline_choices(action: argparse.Action) -> str | None:
    """
    Render choices as an inline '{c1, c2}' block for the Help block or the Choices
    column — e.g. '{ilo, redfish}' — or None if no choices are set.
    """
    ch = action.choices
    if ch is None:
        return None
    if isinstance(ch, (list, tuple)):
        inner = ", ".join(str(x) for x in ch)
        return f"{{{inner}}}" if inner else None
    if isinstance(ch, dict):
        inner = ", ".join(str(k) for k in ch)
        return f"{{{inner}}}" if inner else None
    return f"{{{ch}}}"


def _scan_parser(parser: argparse.ArgumentParser) -> list[dict[str, Any]]:
    """
    Walk every argparse action registered on *parser* and return a structured
    metadata list.

    Each element carries::
        item_type   'opt' | 'positional'
        name        flag name without '--'/'-' prefix, or dest for positional
        type        '--iso-dir ISO_DIR, -o OUTPUT_DIR'  (opt)
                    'FILE'  (positional metavar)
        choices     '{ilo, redfish}'  (if choices set)
        help_descr  action.help string or ''
        has_short   True when a single-char alias is present
        is_bool     True for store_true / store_false (no type cell)
        default     default value string or None
    """
    table: list[dict[str, Any]] = []
    for action in parser._actions:
        # Skip -h/--help itself and subparser action groups
        if isinstance(action, argparse._HelpAction):
            continue

        is_bool       = _is_true_bool_action(action)
        help_str      = action.help or ""
        display_name  = _action_name(action)
        has_short     = _action_has_short(action)
        default_str   = _action_default_str(action)
        choices_str   = _action_inline_choices(action)

        if action.option_strings:
            meta_str = _action_opt_str(action)
            table.append({
                "item_type":    "opt",
                "name":         display_name,         # e.g. 'method'
                "type":         meta_str,              # e.g. '--method {ilo,redfish}, -m {ilo, redfish}'
                "choices":      choices_str,           # '{ilo, redfish}' or None
                "help_descr":   help_str,
                "has_short":    has_short,
                "is_bool":      is_bool,
                "default":      default_str,
            })
        else:
            # Positional argument
            meta = action.metavar or action.dest.upper() or ""
            table.append({
                "item_type":    "positional",
                "name":         display_name,
                "type":         str(meta),             # e.g. 'server_name'
                "choices":      choices_str,
                "help_descr":   help_str,
                "has_short":    False,
                "is_bool":      False,
                "default":      None,
            })

    return table


def capture_help(fn: Any) -> str:
    """Run the help-printing entry-point and capture the formatted help text.

    The called function (``fn``) is an argparse-based ``main()`` that invokes
    ``parser.parse_args()`` which triggers ``parser.exit()`` → ``sys.exit()``.
    We suppress the resulting ``SystemExit`` and parse the traceback to find
    the argparse ``ArgumentParser`` object from the *caller's* frame (where the
    parser was created as a local), giving us direct access to the parser as a
    primary source of structured argument metadata.
    """
    # ── 1. Capture stdout during fn() execution ────────────────────────────────
    _old_stdout = sys.stdout
    _old_argv = sys.argv[:]
    _old_exit = sys.exit

    captured = io.StringIO()
    sys.stdout = captured
    sys.argv = ["", "--help"]

    exc_arg_table: list[dict[str, Any]] = []
    exc_help: str = ""

    try:
        fn()
    except SystemExit as exc:
        # fn() called parser.print_help() then parser.exit() → SystemExit
        exc_help = captured.getvalue()

        # ── 2. Find the argparse ArgumentParser from the traceback ───────────────
        # SystemExit propagates through |fn() → capture_help|.  The exception
        # __traceback__ retains every unwound frame, so walking it backwards
        # from the handler finds the caller's |main()| frame (parser is a local
        # there) before argparse internals.
        tb = exc.__traceback__
        while tb is not None:
            frame = tb.tb_frame
            snapshot = list(frame.f_locals.values())
            for val in snapshot:
                if (isinstance(val, argparse.ArgumentParser)
                        and getattr(val, "prog", None) is not None):
                    exc_arg_table = _scan_parser(val)
                    break
            else:
                tb = tb.tb_next
                continue
            break  # parser found → stop walking
    finally:
        sys.stdout = _old_stdout
        sys.argv = _old_argv
        sys.exit = _old_exit  # type: ignore[assignment]

    return exc_help, exc_arg_table


def _choice_helper(first_word: str) -> tuple[str | None, str | None]:
    """
    Attempt to parse a 'CHOICE' or '{choice,...}' prefix from *first_word*.

    Returns
    -------
    (inline_choices_str | None, next_token | None)
        inline_choices_str  e.g.  '{ilo, redfish}'   or   '{python || yaml}'
        next_token           first non-{...} token or None
    """
    if not first_word or not first_word.startswith("{"):
        return None, None
    bracket_end = first_word.find("}")
    if bracket_end < 0:
        return None, None
    choices_body = first_word[1:bracket_end]
    # Normalise separator: argparse uses ',' or '||' to join choices
    parts = [p.strip() for p in choices_body.replace("||", ",").split(",") if p.strip()]
    inner = ", ".join(parts)
    rest = first_word[bracket_end + 1:].strip().rstrip(",").strip() or None
    return (f"{{{inner}}}" if inner else None), rest


def _opt_is_good_start(token: str, after: str) -> bool:
    """
    True when *token* starts OR continues an argparse option-cell in the one-column
    formatted help line.

    The formatted argparse help shows optional args in one of these forms:
      '--iso-dir ISO_DIR'
      '--method {ilo,redfish}'
      '--iso-dir ISO_DIR, -o OUTPUT_DIR'
      '--dry-run'
      '{python,yaml}'

    *after* is the part of the stripped line after this token (may be '').
    """
    if not token:
        return False
    leading = token[0]
    # argparse tokens start with '-'  or  '{'  (choices inline).
    return leading in {"-", "{"} or (leading in "_" and len(token) > 1)


def _opt_name(token: str) -> str | None:
    """
    Return the canonical dash-stripped name for an option token, or None.

    '--method'  ->  'method'
    '-m'        ->  'm'
    '{python}'  ->  None  (bare choices — not an option name)
    'ISO_DIR'   ->  None  (metavar — not an option name)
    """
    if not token:
        return None
    if token[0] in "-_":
        return token.lstrip("-")
    return None   # metavar, help prose, anything else


def _mt_parts(tokens: list[str]) -> tuple[str, list[str]]:
    """
    Split a raw help-row token list into (canonical metavar, remaining-help-words)
    for a token sequence that represents one logged-in-options...

    *tokens*  is ``stripped.split()`` from one help-row.
    Returns
    -------
    (metavar, remaining_words)  where remaining_words may be empty.
    """
    if len(tokens) <= 2:
        return "", tokens[2:] if len(tokens) > 2 else []

    # tokens here are [--iso-dir, ISO_DIR, -o, OUTPUT_DIR]  OR
    #                [--iso-dir, ISO_DIR, Directory, containing, ...]
    # The first token = option name (already stripped of '-').
    # The second token onwards = metavar-then/OR-help-then or short-alias-then.
    i = 1                                               # index after '--name'
    mt_tok = tokens[i] if i < len(tokens) else ""

    # If tokens[i] looks like a short alias "-s" strip it from metavar extraction
    if mt_tok and len(mt_tok) == 2 and mt_tok[0] == "-":
        i += 1
        mt_tok = tokens[i] if i < len(tokens) else ""

    return mt_tok, tokens[i + 1:] if i + 1 < len(tokens) else []


def _is_action_section_header(ts: str) -> bool:
    """Return True if the full line *ts* (after strip) is a known argparse
    section header that marks a boundary rather than an item row."""
    return ts.strip() in {
        "usage:",
        "positional arguments:",
        "optional arguments:",
        "options:",
    }


def extract_args_from_help(help_text: str) -> list[dict[str, Any]]:
    """
    Parse a raw ``python <script> --help`` string by :mod:`argparse` and return
    a structured list of argument metadata dicts.

    Strategy
    ────────
    argparse embeds the argument list inside one or two well-delimited blocks:

    • ``positional arguments:`` — positional args, one per line
    • ``options:`` / ``optional arguments:`` — optional args, one per line

    Both blocks begin on a new line after the section header.  Each row starts
    at column 0 with a ``--`` (optional), ``-x`` (optional), or a plain
    positional name.  A single continuation row (the description prose) may
    follow, indented beneath its option row — this line begins with spaces and
    its first non-space token is definitely *not* a ``-`` flag or ``{`` choices,
    so it is merged as description text.

    Prose rows at column 0 inside ``options:`` (e.g. the short description line
    "Deploy ISOs to HPE ProLiant servers") are *skipped*; they are not argparse
    items.

    Returns
    -------
    list of dict with keys:
        item_type      'opt' | 'positional'
        name           flag / dest name (no dashes)
        type           '--iso-dir ISO_DIR, -o OUTPUT_DIR'  (opt with metavar)
                        '{enable, disable, validate}'  (choices inline)
                        ''                              (boolean flag)
                        'SERVER'                         (positional metavar)
        choices        '{ilo, redfish}'  or None  (inline choices block)
        help_descr     description prose from argparse
        has_short      True when a single-char alias exists
        is_bool        True for store_true / store_false / store_const *without* metavar
        default        literal default shown in argparse help, or None
     """
    # ── State ───────────────────────────────────────────────────────────────────
    args: list[dict[str, Any]] = []
    lines = help_text.splitlines()
    current: dict[str, Any] | None = None

    enter_opt = "options"
    enter_pos = "positional arguments"

    def parse_inline_choices(token: str) -> tuple[str | None, str | None]:
        """
        From a raw token like ``{ilo,redfish}`` or ``{python || yaml}``
        extract the choices-block and any trailing text.
        """
        if token[:1] != "{" or "}" not in token:
            return None, None
        rb = token.index("}")
        inner = token[1:rb].replace("||", ",")
        parts = [p.strip() for p in inner.split(",") if p.strip()]
        return ("{" + " ".join(parts) + "}" if parts else None,
                token[rb+1:].strip() or None)

    def _sec_key(s: str) -> str:
        return s.strip().rstrip(":")

    def close_current() -> None:
        nonlocal current
        if current:
            args.append(current)
            current = None

    def make_opt(canon: str, opt_str: str, choices_s: str | None,
                 help_s: str, has_sh: bool, is_bool: bool) -> dict:
        return {
            "item_type": "opt",
            "name":       canon,
            "type":       opt_str,
            "choices":    choices_s,
            "help_descr": help_s,
            "has_short":  has_sh,
            "is_bool":    is_bool,
            "default":    None,
        }

    def make_pos(name: str, type_s: str, help_s: str) -> dict:
        return {
            "item_type":  "positional",
            "name":       name,
            "type":       type_s,
            "choices":    None,
            "help_descr": help_s,
            "has_short":  False,
            "is_bool":    False,
            "default":    None,
        }

    # ── Prose-row detection ──────────────────────────────────────────────────────
    def _indent_len(raw: str) -> int:
        """ASCII spaces at the start of *raw* (up to first non-space char)."""
        return len(raw) - len(raw.lstrip(" "))

    def _is_prose_row(raw: str, indent_len: int, prose_group_depth: int) -> bool:
        """
        True when *raw* looks like argparse description prose (a continuation
        row) rather than the start of a new argparse option row.

        ``prose_group_depth`` is the deepest common indentation seen so far,
        or 0 when no prose block has been started yet.
        """
        if not raw or not raw.strip():
            return False
        if prose_group_depth > 0:
            # Already tracking a multi-row prose block: rows indent > current
            # prose depth are more prose; rows at the depth MAYBE are a new item.
            return indent_len >= prose_group_depth
        return False

    def _merge_adjacent_prose(current: dict | None, stripped: str) -> dict | None:
        """
        Merge a prose line ``stripped`` into *current*'s help_descr if current
        is set; otherwise return None (caller should skip this row).
        """
        if current and stripped:
            current["help_descr"] += " " + stripped
            return current
        return None

    # ── State ───────────────────────────────────────────────────────────────────
    args: list[dict[str, Any]] = []
    lines = help_text.splitlines()
    current: dict[str, Any] | None = None
    section_name: str | None = None
    # ── Prose tracking ──────────────────────────────────────────────────────────
    prose_group_depth: int = 0
    in_prose_mode: bool = False          # True when multi-row prose is active
    prose_stack: list[int] = []

    def _push_prose_depth(depth: int) -> None:
        nonlocal prose_group_depth, in_prose_mode
        if depth > prose_group_depth:
            prose_group_depth = depth
            in_prose_mode = True
            prose_stack.append(depth)

    def _pop_prose_depth() -> None:
        nonlocal prose_group_depth, in_prose_mode
        prose_stack.pop()
        prose_group_depth = prose_stack[-1] if prose_stack else 0
        in_prose_mode = bool(prose_stack)

    for raw in lines:
        stripped = raw.strip()
        if not stripped:
            continue

        sk = _sec_key(stripped)
        is_enter_opt  = sk == enter_opt or sk == "optional arguments"
        is_enter_pos  = sk == enter_pos

        # ── Section header ──────────────────────────────────────────────────────
        if is_enter_opt or is_enter_pos:
            close_current()
            prose_group_depth = 0
            in_prose_mode = False
            prose_stack.clear()
            section_name = enter_opt if is_enter_opt else enter_pos
            continue

        if section_name is None:
            # Col-0 prose before any named section (description after ``usage:``)
            continue

        # ── Compute indentation ──────────────────────────────────────────────────
        is_short_row = raw.startswith(" ")   # space-indented from col 0

        # ── Option / prose row ───────────────────────────────────────────────────
        if section_name in (enter_opt, enter_pos) and is_short_row:
            toks = stripped.split()
            if toks and (toks[0][0] == "-" or toks[0][0] == "{"):
                # Indented option or bare-choice: treat same as col-0 row below
                pass   # falls through to row-type detection
            else:
                # Indented prose row: merge into current or track as prose block
                if in_prose_mode and current:
                    # Multi-row prose continuation: depth already >= prose_group_depth
                    _merge_adjacent_prose(current, stripped)
                elif current and prose_group_depth == 0:
                    # First prose row after the option: ρ
                    depth = _indent_len(raw)
                    if depth > 0:
                        _push_prose_depth(depth)
                        _merge_adjacent_prose(current, stripped)
                # else true prose or unrecognised: skip
                continue

        # ── Col-0 option row ────────────────────────────────────────────────────
        toks = stripped.split()
        if not toks:
            continue

        ft = toks[0]

        # In options mode, col-0 words that don't start with '-' or '{'
        # are prose (e.g. RawDescription help prose between section header
        # and first option). Skip them.
        if section_name == enter_opt and ft[0] != "-" and ft[0] != "{":
            continue

        # ── Close any previous entry ────────────────────────────────────────────
        close_current()

        # ── Option row (--flag or -x) ───────────────────────────────────────────
        if ft[0] == "-":
            rest = toks[1:]
            canon = ft.lstrip("-").rstrip(",")      # Bug A: strip trailing comma
            has_short = False
            type_words: list[str] = []
            help_words: list[str] = []
            choices_str: str | None = None

            for tok in rest:
                if tok in (",", "or"):
                    continue
                cs, rest_of = parse_inline_choices(tok)
                if cs and not choices_str:   # Bug C: capture choices only once per row
                    choices_str = cs
                    if rest_of:
                        help_words.append(rest_of)
                    continue
                if len(tok) == 2 and tok[0] == "-":
                    has_short = True
                    type_words.append(tok)
                    continue
                type_words.append(tok)

            # ── Separate inline prose from type/meta tokens in single-row format ────
            # Short-flag inline format places description prose on the SAME row
            # as the invocation ball (e.g. '  --server, -s SERVER   Build for...').
            # Only scan for prose when we're NOT already tracking a multi-row
            # prose block (in_prose_mode == False); multi-row uses indented rows,
            # which are merged via _merge_adjacent_prose below.
            if not in_prose_mode:
                # Strategy: scan backwards from the token end.  Tokens whose text
                # anchor in the stripped row at or before col 0 are invocation tokens;
                # everything past the last such token is prose that leaked into the
                # same helpful row.
                text = stripped
                last_parts: list[str] = []   # tokens that anchor as invocation tokens

                i = len(type_words) - 1
                while i >= 0:
                    tok = type_words[i]
                    if tok in (",",) or (len(tok) == 2 and tok[0] == "-"):
                        i -= 1
                        continue
                    s = text.find(tok, 0)
                    if s >= 0:
                        last_parts.append(tok)
                    i -= 1

                if last_parts:
                    inv_parts = list(reversed(last_parts))
                    prose_parts = type_words[len(inv_parts):]
                    type_words = inv_parts
                    if prose_parts:
                        help_words.extend(prose_parts)

            mt = " ".join(type_words).strip()
            segments: list[str] = [ft]
            if choices_str:
                segments.append(choices_str)
            elif mt:
                segments.append(mt)
            if has_short:
                short_raw = next(  # use local short-flag from type_words
                    (t for t in rest if len(t) == 2 and t[0] == "-"), "")
                if short_raw:
                    segments.append(short_raw)
            opt_txt = " ".join(segments)
            help_txt = " ".join(help_words).strip()

            current = make_opt(
                canon=canon,
                opt_str=opt_txt,
                choices_s=choices_str,
                help_s=help_txt,
                has_sh=has_short,
                is_bool=(choices_str is None and not mt and not has_short),
            )

        # ── Bare inline-choices row '{…}' ──────────────────────────────────────
        elif ft[0] == "{":
            cs, _ = parse_inline_choices(ft)
            rest_desc = " ".join(toks[1:]).strip()
            existing = (current["name"] if current else None) or "option"
            current = make_opt(
                canon=existing,
                opt_str=cs or ft,
                choices_s=cs,
                help_s=rest_desc,
                has_sh=False,
                is_bool=False,
            )

        # ── Positional name ─────────────────────────────────────────────────────
        else:
            close_current()
            pos_meta = toks[1] if len(toks) > 1 else ""
            pos_help = " ".join(toks[2:]).strip() if len(toks) > 2 else ""
            current = make_pos(
                name=ft,
                type_s=pos_meta or ft.upper(),
                help_s=pos_help,
            )

    close_current()
    return args


# ── Markdown rendering ────────────────────────────────────────────────────────

def _fmt_preamble(cmd: CmdDoc) -> list[str]:
    """Front-matter + title."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return [
        "---",
        f"source:      {cmd.module_path}::main()",
        f"console_script: {cmd.script_name}",
        f"generated:   {ts}",
        "auto_generated_by: scripts/generate_python_docs.py",
        "---",
        "",
        f"# `{cmd.script_name}`",
        "",
    ]


def _fmt_description(cmd: CmdDoc) -> list[str]:
    """## Description section from module docstring."""
    out: list[str] = []
    if cmd.docstring:
        out += ["## Description", ""]
        for para in cmd.docstring.strip().splitlines():
            out.append(para)
        out.append("")
    return out


def _fmt_preamble_args(raw_help: str) -> tuple[str | None, str | None]:
    """Extract the ``usage:`` line and its description prose from the raw help text."""
    prog: str | None = None
    desc: str | None = None
    for line in raw_help.splitlines():
        s = line.strip()
        if not s:
            continue
        if prog is None:
            if s.startswith("usage:"):
                prog = s
            elif desc is None and not s.startswith("usage:"):
                desc = s
        if prog and desc:
            break
    return prog, desc


def _fmt_keywords(args_meta: list[dict[str, Any]]) -> list[str]:
    """
    Build the ## Keywords block listing argument names and key descriptors.

    Lists the items as `>-name` — type / choices / default — for quick scanning.
    Skips bool flags (no useful type or default column).
    """
    lines: list[str] = ["", "## Keywords", ""]
    has_any = False
    for arg in args_meta:
        has_any = True
        name_disp = f"-{arg['name'].rstrip(',')}"  # strip trailing comma from canon name
        desc_parts: list[str] = []

        type_str = arg.get("type", "")
        if type_str:
            desc_parts.append(type_str)

        if arg["is_bool"]:
            desc_parts.append("*(boolean flag)*")

        choices_str = arg.get("choices")
        if choices_str:
            desc_parts.append(f"choices: {choices_str}")

        default = arg.get("default")
        if default is not None:
            desc_parts.append(f"default: `{default}`")

        full_desc = "; ".join(desc_parts) if desc_parts else ""
        if full_desc:
            lines.append(f"- `{name_disp}`  —  {full_desc}")
        else:
            lines.append(f"- `{name_disp}`")

    if not has_any:
        return []
    return lines


def _fmt_parameters(args_meta: list[dict[str, Any]]) -> list[str]:
    """
    Build the ## Parameters Markdown table.

    Renders each option flag and positional argument as a single table row.
    Matches the two-column PowerShell style (Parameter | Description) but includes
    the expected type/metavar in the left-hand cell for extra clarity.

    Row formats:
      Flags with a metavar                --iso-dir ISO_DIR   |  Dir description  |
      Boolean flags (no metavar)          --dry-run           |  Description only |
      Flags with {choices} inline         --method {ilo,redfishredfish}   |  Description: 'ilo', 'redfish' |
      Positional args (type shown as loc) server_name        |  Desc  |
    """
    if not args_meta:
        return []

    lines: list[str] = ["", "## Parameters", ""]

    for arg in args_meta:
        # ── Name cell ──────────────────────────────────────────────────────
        canon = arg['name'].rstrip(',')  # strip trailing comma from canon name
        name_disp = f"`-{canon}`" if arg["item_type"] == "opt" else f"`{canon}`"

        # ── Type / metavar annotation in parens ─────────────────────────────
        type_col = arg.get("type", "")
        type_part = f" ({type_col})" if type_col else ""

        # ── Description cell: help prose first, then choices annotation ────
        desc_parts: list[str] = []
        help_descr = (arg.get("help_descr") or "").strip()
        if help_descr:
            desc_parts.append(help_descr)

        choices_str = arg.get("choices")
        if choices_str:
            desc_parts.append(f"*(choices: {choices_str})*")

        default = arg.get("default")
        if default is not None:
            desc_parts.append(f"default: `{default}`")

        desc_col = " ".join(desc_parts) if desc_parts else "—"

        lines.append(f"| {name_disp}{type_part} | {desc_col} |")

    return lines


def _fmt_examples(raw_help: str) -> list[str]:
    """
    Build the ## Examples section from the raw argparse --help text.

    Uses the short description line (first non-empty prose after the
    ``usage:`` line) as Example 1.
    """
    _, desc_line = _fmt_preamble_args(raw_help)

    out: list[str] = ["", "## Examples", ""]
    if desc_line:
        out.append("### Example 1")
        out.append("```shell")
        out.append(desc_line)
        out.append("```")
        out.append("")
    return out


def _fmt_help(raw_help: str) -> list[str]:
    """§ Help  — raw argparse --help output in a fenced code block."""
    if not raw_help:
        return []
    return [
        "## Help",
        "```shell",
        raw_help.strip(),
        "```",
        "",
    ]


def render_markdown(cmd: CmdDoc) -> str:
    # ── Collect section fragments ─────────────────────────────────────────────
    sections: list[str] = []

    # ── Front-matter + title ─────────────────────────────────────────────────
    sections += _fmt_preamble(cmd)

    # ── Description ──────────────────────────────────────────────────────────
    sections += _fmt_description(cmd)

    # ── Keywords ─────────────────────────────────────────────────────────────
    if cmd.arg_table:
        sections += _fmt_keywords(cmd.arg_table)

    # ── Parameters ───────────────────────────────────────────────────────────
    sections += _fmt_parameters(cmd.arg_table)

    # ── Examples ─────────────────────────────────────────────────────────────
    sections += _fmt_examples(cmd.raw_help)

    # ── Help (raw argparse output) ───────────────────────────────────────────
    sections += _fmt_help(cmd.raw_help)

    # ── Footer ───────────────────────────────────────────────────────────────
    sections += [
        "---",
        "*This file is auto-generated by `scripts/generate_python_docs.py`. "
        "Do not edit directly — update code or docstrings and re-run.*",
        "",
    ]

    return "\n".join(sections)


# ── Master INDEX.md builder ───────────────────────────────────────────────────
def write_index(files: list[str]) -> None:
    index_path = DOCS_OUTPUT_DIR / "INDEX.md"
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Python CLI — Generated API Reference",
        "",
        "> Auto-generated by `scripts/generate_python_docs.py` — do not edit manually.",
        "",
        f"Generated: {ts}",
        "",
        "## Commands",
        "",
    ]
    for fn in sorted(files):
        name = Path(fn).stem
        lines.append(f"- [`{name}`]({fn})")
    lines += ["", "---", ""]
    index_path.write_text("\n".join(lines), encoding="utf-8")


# ── Main ───────────────────────────────────────────────────────────────────────
def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Markdown docs for Python CLIs")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .md files")
    parser.add_argument("--output", type=Path, default=DOCS_OUTPUT_DIR, help="Output directory")
    parser.add_argument("--module-root", type=Path, default=SRC_ROOT, help="Project src/ root")
    args = parser.parse_args()

    output_dir: Path = args.output
    output_dir.mkdir(parents=True, exist_ok=True)

    # Ensure src/ is on sys.path so importlib works from any working directory
    if str(SRC_ROOT) not in sys.path:
        sys.path.insert(0, str(SRC_ROOT))

    generated_files: list[str] = []

    for script_name, dotted_path in sorted(CONSOLE_SCRIPTS.items()):
        out_file = output_dir / f"{script_name}.md"

        if out_file.exists() and not args.force:
            print(f"  [SKIP] {script_name}.md (use --force to overwrite)")
            generated_files.append(out_file.name)
            continue

        print(f"  [GENERATE] {script_name}  ({dotted_path})")

        try:
            fn, module_path = load_callable(dotted_path)
        except Exception as exc:
            print(f"    [FAIL] Import error: {exc}", file=sys.stderr)
            continue

        docstring = (fn.__doc__ or "").strip().splitlines()
        docstr = "\n".join(docstring) if docstring else None

        try:
            help_text, exc_arg_table = capture_help(fn)
        except Exception as exc:
            print(f"    [FAIL] Could not capture --help: {exc}", file=sys.stderr)
            help_text = f"(error capturing help: {exc})"
            exc_arg_table = []

        # ── Primary: structured arg metadata from the argparse parser object ────────
        # capture_help() already found the parser via the SystemExit __traceback__
        # and returned _scan_parser() results; this is the authoritative source.
        arg_table: list[dict[str, Any]] = exc_arg_table

        # ── Fallback: plain-text parser (handles edge-cases / non-standard formatters)
        if not arg_table and help_text:
            arg_table = extract_args_from_help(help_text)

        cmd_doc = CmdDoc(
            script_name=script_name,
            module_path=module_path,
            function_name=dotted_path.partition(":")[2],
            docstring=docstr,
            help_text=help_text,
            arg_table=arg_table,
            raw_help=help_text,
        )
        md = render_markdown(cmd_doc)
        out_file.write_text(md, encoding="utf-8")
        generated_files.append(out_file.name)
        print(f"    ✓  {out_file.name}")

    write_index(generated_files)
    print(f"\n[generate_python_docs] {len(generated_files)} file(s) written → {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
