#
# Module manifest for module 'Automation'
#
# Generated by: Kilo
# Source project : HPE ProLiant Windows Server ISO Automation
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'Automation.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID = 'b3d1e2a4-5c6f-4e8a-9b0c-1d2e3f4a5b6c'

    # Author of this module
    Author = 'Kev Everall'

    # Company or vendor of this module
    CompanyName = 'HPE Automation'

    # Copyright statement for this module
    Copyright = '(c) 2026 Kev Everall. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'HPE ProLiant Windows Server ISO Automation - PowerShell module for maintenance mode orchestration, ISO build, firmware updates, security patching, deployment, and monitoring.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of the .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NOTE: Classes are defined in Automation.psm1 (root) to ensure type visibility.
    #       All Private/*.psm1 and Public/*.psm1 files are dot-sourced by Automation.psm1.
    NestedModules = @()

    # Functions to export from this module.
    # '*' exports everything — the root psm1 dot-sources all Private/Public modules.
    FunctionsToExport = '*'

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    # PrivateData = @{ PSData = @{ } }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module.
    # Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
